package com.example.lxy.androiddemo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "CITY".
 */
@Entity
public class City {

    @Id
    private Long id;
    /** Not-null value. */
    private String name;
    private Integer isHot;
    private String alias;

    public City() {
    }

    public City(String name) {
        this.name = name;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Integer getIsHot() {
        return this.isHot;
    }

    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Generated(hash = 1411521768)
    public City(Long id, String name, Integer isHot, String alias) {
        this.id = id;
        this.name = name;
        this.isHot = isHot;
        this.alias = alias;
    }



}
